#!/bin/bash

mess (){
clear
echo "Your message" | aosd_cat -R white -x 430 -y -550 -u 1000 -n "Arial Black 50" -e 12
clear
echo "Your message" | aosd_cat -R white -x 430 -y -550 -u 1000 -n "Arial Black 50" -e 12
echo "Your message" | aosd_cat -R white -x 430 -y -550 -u 1000 -n "Arial Black 50" -e 12
echo "Your message" | aosd_cat -R white -x 430 -y -550 -u 1000 -n "Arial Black 50" -e 12
echo "Your message" | aosd_cat -R white -x 430 -y -550 -u 1000 -n "Arial Black 50" -e 12
}



 while true;
 do 

 mess
 
 sleep 1; done
